name: Weekly Repository Summary Update

on:
  schedule:
    # Run every Sunday at 6:00 AM UTC (cron: minute hour day-of-month month day-of-week)
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggering for testing

permissions:
  contents: write  # Required to push changes back to the repository
  pull-requests: write  # Required if creating PRs instead of direct commits

jobs:
  update-summary:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dateutil
        
    - name: Generate weekly summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        python .github/scripts/generate_summary.py
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "🤖 Weekly repository summary update - $(date +'%Y-%m-%d')"
        git push
        
    - name: Create summary comment
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        echo "✅ Weekly summary updated successfully on $(date +'%Y-%m-%d %H:%M:%S UTC')"
      
    - name: No changes detected
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: |
        echo "ℹ️ No changes detected in repository summary"
